export const INIT_ARTICLES="INIT_ARTICLES"
export const INIT_LABELS="INIT_LABELS"
export const INIT_SORTS="INIT_SORTS"
export const INIT_COMMENTS="INIT_COMMENTS"
export const INIT_BULLET="INIT_BULLET"


export const INIT_MESSAGE="INIT_MESSAGE"
export const DELETE_MESSAGE="DELETE_MESSAGE"


export const INIT_LOGIN="INIT_LOGIN"
export const OUT_LOGIN="OUT_LOGIN"